<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Python (interactive)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(&gt;&gt;&gt;|\.\.\.)\s</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>interactive.prompt.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^Welcome to Python .* help utility!$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>interactive.output.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^You are now leaving help and returning to the Python interpreter.$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>interactive.output.python</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^help&gt;\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>interactive.prompt.python</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(modules|symbols|keywords|topics|quit)\b</string>
							<key>name</key>
							<string>keyword.other.python</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^.*$</string>
					<key>name</key>
					<string>interactive.output.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^Traceback \(most recent call last\):$</string>
			<key>end</key>
			<string>(?=^&gt;&gt;&gt;)</string>
			<key>name</key>
			<string>interactive.output.error.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(([[:alpha:]_][[:alnum:]_]*)?Error:).*</string>
			<key>name</key>
			<string>interactive.output.error.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^.+$</string>
			<key>name</key>
			<string>interactive.output.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.interactive.python</string>
	<key>uuid</key>
	<string>84F21621-E16E-41A6-A398-A29143FFF069</string>
</dict>
</plist>
